name: Release

on:
  push:
    tags:
      - 'v*' # Any tag starting with a v, e.g. v4.0.0
  workflow_dispatch: # Allows manual triggering from the GitHub Actions tab

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    environment:
      name: release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Test with Coverage
        run: yarn test

      - name: Build project
        run: yarn build

      - name: Archive entire project
        run: |
          rm -f latest.tar.gz latest.zip

          tar \
            --exclude='./.git' \
            --exclude='./node_modules' \
            -czf "$RUNNER_TEMP/latest.tar.gz" .

          zip -r "$RUNNER_TEMP/latest.zip" . \
            -x './.git/*' \
            -x './node_modules/*'

          mv "$RUNNER_TEMP/latest.tar.gz" latest.tar.gz
          mv "$RUNNER_TEMP/latest.zip" latest.zip

      - name: Create Release and Upload Artifact
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            dist/*
            latest.tar.gz
            latest.zip
          token: ${{ secrets.RELEASE_TOKEN }}
